## Import Numpy

In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3])

In [18]:
b = np.array([[1,2,3,4,6,7,8],
             [5,6,7,8,12,11,19]])

In [11]:
b.ndim

2

In [19]:
b.size

14

In [21]:
a.shape

(3,)

In [20]:
b.shape

(2, 7)

In [22]:
c = np.array([[[1,2],[3,4],[6,7]],
             [[5,6],[7,8],[12,11]]])

In [28]:
b[0,3]

4

In [29]:
c[0,1,1]

4

In [97]:
d = np.array([[1,2,3,4,5,6],
            [7,8,9,10,11,12],
            [13,14,15,16,17,18],
            [19,20,21,22,23,24]])

In [96]:
d[1,2:7:2]

array([ 9, 11])

awal:akhir:stepsize

In [54]:
d[0:2,::2] = [[0,0,0],[0,0,0]]

In [48]:
d[[0,1,2,3],[4,2,4,5]] = [0,0,0,0]

In [55]:
d

array([[ 0,  2,  0,  4,  0,  6],
       [ 0,  8,  0, 10,  0, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

# Buat array

In [60]:
fungsi_nol = np.zeros((3,2,5))

In [61]:
fungsi_nol

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [65]:
fungsi_satu = np.ones((2,3),dtype = "int16")

In [66]:
fungsi_satu.dtype

dtype('int16')

In [67]:
fungsi_satu

array([[1, 1, 1],
       [1, 1, 1]], dtype=int16)

In [68]:
fungsi_full = np.full((2,3),8)

In [69]:
fungsi_full

array([[8, 8, 8],
       [8, 8, 8]])

In [70]:
fungsi_pengganti = np.full_like(d, 10)

In [71]:
fungsi_pengganti

array([[10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10]])

In [83]:
c=np.random.rand(4,2)

In [84]:
c

array([[0.13168832, 0.14968239],
       [0.69153574, 0.20463648],
       [0.19389343, 0.76751438],
       [0.83165507, 0.39981499]])

In [85]:
c=(c-0.5)*100

In [86]:
c

array([[-36.83116766, -35.03176073],
       [ 19.15357383, -29.53635176],
       [-30.61065694,  26.75143849],
       [ 33.16550707, -10.01850081]])

In [87]:
c = np.random.randint(-4,6, size =(2,3))

In [88]:
c

array([[-2,  0, -1],
       [-2,  5,  2]])

In [91]:
d = np.identity(6, dtype = "int64")

In [92]:
d

array([[1, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 1]], dtype=int16)

In [123]:
d = np.array([[1,2,3,4,5,6],
            [7,8,9,10,11,12],
            [13,14,15,16,17,18],
            [19,20,21,22,23,24]])

In [127]:
d_kali = np.full((6,3),5)

In [128]:
d

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [129]:
d_kali

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5],
       [5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [130]:
hasil = np.matmul(d,d_kali)

In [131]:
hasil

array([[105, 105, 105],
       [285, 285, 285],
       [465, 465, 465],
       [645, 645, 645]])

In [133]:
c = np.random.randint(1,4,size =(4,4))

In [134]:
c

array([[3, 3, 1, 1],
       [3, 1, 2, 3],
       [1, 2, 2, 3],
       [1, 1, 1, 1]])

In [135]:
np.linalg.det(c)

6.0

In [136]:
np.linalg.inv(c)

array([[ 0.16666667,  0.33333333, -0.33333333, -0.16666667],
       [ 0.33333333, -0.33333333,  0.33333333, -0.33333333],
       [-0.66666667, -0.33333333, -0.66666667,  3.66666667],
       [ 0.16666667,  0.33333333,  0.66666667, -2.16666667]])

In [137]:
d

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [138]:
d.reshape(3,8)

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24]])

In [139]:
d.reshape(2,12)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [140]:
d.reshape(12,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14],
       [15, 16],
       [17, 18],
       [19, 20],
       [21, 22],
       [23, 24]])

In [141]:
np.max(d)

24

In [142]:
np.min(d)

1

In [143]:
d

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [154]:
np.max(d,axis=0)

array([19, 20, 21, 22, 23, 24])